
public class Exception{  
public void finalize(){System.out.println("finalize called");}  
}  
